services:
  database:
    image: mysql:9.0.0
    environment:
      MYSQL_ROOT_PASSWORD: local_password
      MYSQL_DATABASE: local_database
      MYSQL_USER: user
      MYSQL_PASSWORD: local_password
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my_phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    depends_on:
      - database
